# See https://pre-commit.com for more information
# See https://pre-commit.com/hooks.html for more hooks
repos:
# This can be used to check how pre-commit is being run
# - repo: meta
#   hooks:
#   - id: identity

-   repo: https://github.com/pre-commit/pre-commit-hooks
    rev: 'v4.1.0'
    hooks:
      - id: check-merge-conflict 
      - id: debug-statements 
      - id: end-of-file-fixer 
      - id: mixed-line-ending
      - id: check-yaml

        #-   repo: https://github.com/pre-commit/mirrors-autopep8
        #    rev: ''
        #    hooks:
        #      - id: autopep8

### # flake8 --show-source <file>
### -   repo: https://gitlab.com/pycqa/flake8
###     rev: ''
###     hooks:
###       - id: flake8
#
# Try using local flake8
- repo: local
  hooks:
    - id: flake8
      name: flake8
      entry: flake8
      language: system
      types: [ python ]

-   repo: https://github.com/pre-commit/pygrep-hooks
    rev: 'v1.9.0'
    hooks:
      - id: python-no-eval 
      - id: python-no-log-warn 
# This is a pain where a comment begins with the word 'type' otherwise
#      - id: python-use-type-annotations 

# mypy - static type checking
# mypy --follow-imports skip <file>
-   repo: https://github.com/pre-commit/mirrors-mypy
    rev: 'v0.931'
    hooks:
      - id: mypy
        # verbose: true
        # log_file: 'pre-commit_mypy.log'
        additional_dependencies: [ types-requests ]
        # args: [ "--follow-imports", "skip", "--ignore-missing-imports", "--scripts-are-modules" ]

default_language_version:
    python: python3.10

default_stages: [ commit, push ]

#files: '([^\.].+/)*.py'
